### ISSUE TITLE
La classe nonpknfojebnofkjewdfewwqdwdw

### ISSUE THREAD

**Issue by filippobonfanti** [LucaRossi801/progetto_ingsw#1]
!URGENTE!
Sono drissi bilal bipal grissino
![image](https://github.com/user-attachments/assets/30df13ca-2eff-4e55-a7fa-a5aef8208191)

CONTROLLA CELERMENTE!!!!!!!!!

**Comment by LucaRossi801** [comment]
alà pagliaccio.

**Comment by filippobonfanti** [comment]
hai ragione, sono un bigol
